# Generated by Django 3.1 on 2025-03-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbbonamentiIncontri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'abbonamenti_incontri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Insegnanti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('data_nascita', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Utenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('data_nascita', models.DateField()),
                ('indirizzo', models.CharField(max_length=255)),
                ('emailIndex', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('foto', models.TextField()),
                ('usernameIndex', models.CharField(max_length=50)),
                ('password_utente', models.CharField(max_length=255)),
                ('data_registrazione', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Incontri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_disciplinaIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_palestra.discipline')),
                ('fk_id_insegnanteIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_palestra.insegnanti')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='insegnante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_palestra.insegnanti'),
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_incontro', models.DateField()),
                ('ora_inizio_incontro', models.TimeField()),
                ('ora_fine_incontro', models.TimeField()),
                ('incontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_palestra.incontri')),
            ],
        ),
        migrations.CreateModel(
            name='Abbonamenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sedute', models.IntegerField()),
                ('stato_pagamento', models.CharField(max_length=255)),
                ('costo_totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incontro', models.ForeignKey(db_column='fk_id_incontro', on_delete=django.db.models.deletion.CASCADE, to='web_palestra.incontri')),
                ('utenti', models.ForeignKey(db_column='fk_id_utente', on_delete=django.db.models.deletion.CASCADE, to='web_palestra.utenti')),
            ],
        ),
    ]
